---
- name: my test play book
  hosts: all
  become: true

  tasks:
    - name: installing httpd package
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: starting httpd service
      service:
        name: docker
        state: started
      when: ansible_os_family == "RedHat"


    - name: installing apache2 package
      apt: 
        name: apache2 
        state: present
      when: ansible_os_family == "Debian"


    - name: start service apache2
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name:
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        owner: maahesh
       
        

