---
- name: My test play book
  hosts: all
  become: true


  tasks:
    - name: pkg installation
      yum:
        name: httpd
        state: present

    - name: start service
      service:
        name: httpd
        state: started
