---
- name: My test playbook
  hosts: all
  become: true
  
  tasks:
    - name: installing apche2 for Redhat
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"

    - name: install apache2 for Debian
      command: apt-get install apache2 -y
      when: ansible_os_family == "Debian"
